# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='milestone',
            fields=[
                ('milestone_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('information', models.TextField(max_length=5000)),
                ('date_creation', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('user_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='88duf9guudfgh+', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='234fdg243gf3+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='milestone_component_connection',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('component_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component')),
                ('milestone_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='milestone_system_connection',
            fields=[
                ('id_sc', models.AutoField(primary_key=True, serialize=False)),
                ('milestone_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.milestone')),
                ('system_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.System')),
            ],
        ),
        migrations.CreateModel(
            name='milestone_task',
            fields=[
                ('ms_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('information', models.TextField(max_length=5000)),
                ('date_creation', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.milestone')),
                ('user_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='884jh56lz4igdrfz+', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aseawerwejkzughjfghhncvb+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
